name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_lint_rules: ^1.5.0
  dart_code_metrics: ^4.13.0

flutter:
  uses-material-design: true

  assets:
    - res/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Black.ttf
        - asset: res/fonts/Roboto-BlackItalic.ttf
        - asset: res/fonts/Roboto-Bold.ttf
        - asset: res/fonts/Roboto-BoldItalic.ttf
        - asset: res/fonts/Roboto-Italic.ttf
        - asset: res/fonts/Roboto-Light.ttf
        - asset: res/fonts/Roboto-LightItalic.ttf
        - asset: res/fonts/Roboto-Medium.ttf
        - asset: res/fonts/Roboto-MediumItalic.ttf
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Thin.ttf
        - asset: res/fonts/Roboto-ThinItalic.ttf